# SRA Download, QC, and Trimming

[Bioinformatics - SRA Download, QC, and Trimming](https://www.youtube.com/watch?v=UkrUTgAKFiE&list=PL-0fKymgD8L8qW7SQDaEf3lrSyUkEkR1k&index=2).

1.  Create environment.
1.  Init environment
1.  `conda install sra-tools` This will allow us to pull directly from the sra page. (where the sample ex. Files)

  a.  Go to [page](https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP061386&o=acc_s%3Aa).
  b.  Select only files needed.
  c.  Then in the Selected > click on Accession List >
  d.  Save
  e.  Drag onto the file structure, so its now in system
  f.  `ls` to see the files (SRR_Acc_List.txt)
  g.  Check 'head SRR_Acc_List.txt' command
  h.  Also you can use the `vi SRR_Acc_List.txt` command to see the list in the file. Ex.

    ①. SRR2121770\
    ②. SRR2121771\
    ③. SRR2121774\
    ④. SRR2121778\
    ⑤. Etc.

4.  Now that we have the list of files, we have to individually download each one of them.  

  a. One way to do that is with the `fastq-dump --gzi --split-file SRR2121770 &` command.  

     ①. This command will take the SRR2121770 file, and save it as a .gzi file (to save space)    
     ②. it will split the file in forward (1) and Reverse (2), then     
     ③. the "&" sign means that it will run this command in the background.    
     
  b. This will take some time since the file is big. A way to see if the process is finished or not is with the command `jobs`, which gives a list of the jobs in process or nothing if there are not jobs running.\
  c. Another way to do it is with the pipe command, so we don't have to do this process for each file. Use the command `cat SRR_Acc_List.txt | parallel fastq-dump --gzi --split-file {}`.  
  
    ①. This will take the SRR_Acc_List.txt and catalog the list.\    
    ②. Then it will take each of the element in the list "{}" slipt them, and save them as gzi.  
    ③. In the rawReads folder???.. you will have a list of .fastq.gz_1 and .fastq.gz_2 for each element of the list. `…rawReads$ ls`.  
    ④. Each time something is changed in the files, create a new folder and save there so the originals are not modified. Ex. Trimmed.   

5.  Once all files are downloaded, install multiqc. `conda install multiqc`. (if not installed)  
6.  Before running fastqc, create an output directory where to save the processed files. `mkdir rawFastQC` (make sure you are in the right directory before making this folder).  
7.  Then run fastqc: `fastqc -t 64 rawReads/*fastqc.gz -o rawFastQC`  

  a.  This means, process files with fastqc using 64 treads (-t 64) windows/linux virtual machine;  
  b.  by taking all fastqc.gz files in the folder rawReads;  
  c.  and save in the output directory (-o) called rawFastQC.  
  d.  This process will take a long time depending on the number and size of the files.  

8.  Once finished `cd rawFastQC` and check the files `ls`   
9.  Then inside the forlder, run multiqc in `multiqc`.   
10. Once this finished, inside the folder a new "multiqc_report.html" will be created.   
11. Open the files and compare.   

22:29    
**Once this quality control is finished we can pass to the trimming of the samples.**  

1.  Install trimmomatic, `conda install trimmomatic` (if not installed).  
2.  If we are going to trim the files, we need to make a new folder, so exit rawFastQC folder.   `cd..` and `mkdir trimmedReads`, we are going to point trimmomatic the this folder.  
3.  We are going to pull our true adapter sequences to our working directory. Then it will be a lot easier to point trimmomatic to that vs havint to type in the really long path. `cp ~/miniconda3/envs/name_of_environment/share/trimmomatic-0.39-1/adapters/TrueSeq3-PE-2.fa .` (the last point is important, it means that the command will the done in this folder).  
4.  Now run the trimmomatic.  

